
configfile: "config.yaml"

rule all:
    input:
        expand("analysis/diamond_collect/{source}.tsv", source = [ "lanclos", "gtdb", "oceandna" ])

rule get_gtdb_metadata:
    output:
        "analysis/metadata/gtdb.tsv"
    params:
        url = config['gtdb']['metadata']
    shell:
        "curl -sL {params.url} | gzip -cd > {output}"

rule get_gtdb_tree:
    output:
        "analysis/metadata/gtdb_tree.nwk"
    params:
        url = config['gtdb']['tree']
    shell:
        "curl -sL {params.url} > {output}"

rule gtdb_clade:
    input:
        "analysis/metadata/gtdb_tree.nwk"
    output:
        clade = "analysis/metadata/gtdb_clade.nwk",
        tips = "analysis/metadata/gtdb_representatives.txt"
    params:
        taxon = config['taxon']
    conda:
        "envs/r.yaml"
    script:
        "scripts/get_gtdbtk_clade.R"

rule get_oceandna_metadata:
    output:
        "analysis/metadata/oceandna.tsv"
    params:
        url = config['oceandna']['metadata'],
        file = config['oceandna']['metadata_file']
    shell:
        "curl -sL {params.url} | tar xfz - {params.file} -O > {output}"

rule dload_lanclos_metadata:
    output:
        "analysis/metadata/lanclos.xlsx"
    params:
        url = config['lanclos']['metadata']
    shell:
        "curl -sL {params.url} > {output}"

rule dload_oceandna_repr:
    output:
        "analysis/oceandna_data/"
    params:
        url = ""
    shell:
        "wget -O {output} {params.url}"

rule get_lanclos_metadata:
    input:
        "analysis/metadata/lanclos.xlsx"
    output:
        "analysis/metadata/lanclos.tsv"
    conda:
        "envs/xlsx2csv.yaml"
    shell:
        "xlsx2csv -s 1 -d tab {input} {output}"

rule get_lanclos_genomes:
    output:
        "analysis/metadata/lanclos_genomes.zip"
    params:
        url = config['lanclos']['genomes']
    shell:
        "curl -sL {params.url} > {output}"

checkpoint filter_gtdb:
    input:
        tsv = "analysis/metadata/gtdb.tsv",
        txt = "analysis/metadata/gtdb_representatives.txt"
    output:
        tsv = "analysis/metadata/gtdb_filtered.tsv",
        dir = directory("analysis/gtdb_json/")
    params:
        genera = config['genera']
    conda:
        "envs/biopython.yaml"
    script:
        "scripts/filter_gtdb.py"

def chosen_diamond(w):
    if w.source == "oceandna":
        tsv = checkpoints.filter_oceandna.get().output[0]
    elif w.source == "lanclos":
        tsv = checkpoints.filter_lanclos.get().output[0]
    elif w.source == "gtdb":
        tsv = checkpoints.filter_gtdb.get().output['tsv']
    with tsv.open() as file:
        accs = [ line.split()[0] for line in file ]
    return expand("analysis/diamond/{source}/{acc}.outfmt6", source = w.source, acc = accs)

def chosen_faa_IIIa(w):
    files = []
    with checkpoints.filter_oceandna.get().output[0].open() as file:
        accs = [ line.split()[0] for line in file ]
        files += expand("analysis/proteins/oceandna/{acc}.faa", acc = accs)
    with checkpoints.filter_lanclos.get().output[0].open() as file:
        accs = [ line.split()[0] for line in file ]
        files += expand("analysis/proteins/lanclos/{acc}.faa", acc = accs)
    with checkpoints.filter_gtdb.get().output['tsv'].open() as file:
        accs = []
        genera = list(config['genera'].values()) + [ config['outgroup'] ]
        for line in file:
            acc, taxonomy, biosamples = line.split('\t')
            for genus in genera:
                if f"{genus};" in taxonomy:
                    accs.append(acc)
        files += expand("analysis/proteins/gtdb/{acc}.faa", acc = accs)
    return files

rule cat_queries:
    input:
        "input/TAT.faa", "input/PR.faa"
    output:
        "analysis/diamond/queries.faa"
    shell:
        "cat {input} > {output}"

rule diamond:
    input:
        query = "analysis/diamond/queries.faa",
        db = "analysis/proteins/{source}/{acc}.faa"
    output:
        "analysis/diamond/{source}/{acc}.outfmt6"
    conda:
        "envs/diamond.yaml"
    shell:
        "diamond blastp -k 0 --sensitive --db {input.db} --query {input.query} --out {output} --outfmt 6"

rule prodigal:
    input:
        "analysis/genomes/{source}/{acc}.fna"
    output:
        faa = "analysis/proteins/{source}/{acc}.faa",
        gff = "analysis/proteins/{source}/{acc}.gff"
    shadow:
        "minimal"
    conda:
        "envs/prodigal.yaml"
    shell:
        "prodigal -i {input} -a {output.faa} -f gff -o {output.gff}"

rule collect_diamond:
    input:
        chosen_diamond
    output:
        "analysis/diamond_collect/{source}.tsv"
    params:
        evalue = 1e-10,
        pident = 48
    conda:
        "envs/r.yaml"
    script:
        "scripts/collect_diamond.R"

checkpoint filter_lanclos:
    input:
        "analysis/metadata/lanclos.tsv"
    output:
        "analysis/metadata/lanclos_filtered.tsv"
    params:
        genera = config['genera']
    conda:
        "envs/biopython.yaml"
    script:
        "scripts/filter_lanclos.py"

checkpoint filter_oceandna:
    input:
        oceandna = "analysis/metadata/oceandna.tsv",
        gtdb = "analysis/metadata/gtdb_filtered.tsv"
    output:
        "analysis/metadata/oceandna_filtered.tsv"
    params:
        genera = config['genera']
    conda:
        "envs/biopython.yaml"
    script:
        "scripts/filter_oceandna.py"

rule get_gtdb_genome:
    input:
        "analysis/gtdb_json/"
    output:
        "analysis/genomes/gtdb/{acc}.fna"
    params:
        json = "analysis/gtdb_json/{acc}_assembly.json"
    resources:
        ncbi = 1
    conda:
        "envs/biopython.yaml"
    script:
        "scripts/get_assembly.py"

rule get_oceandna_genome:
    input:
        "data/oceandna"
    output:
        "analysis/genomes/oceandna/{acc}.fna"
    shell:
        "find -L {input} -name {wildcards.acc}.fa.gz | xargs gzip -cd > {output}"

rule get_lanclos_genome:
    input:
        "analysis/metadata/lanclos_genomes.zip"
    output:
        "analysis/genomes/lanclos/{acc}.fna"
    shell:
        "unzip -p {input} {wildcards.acc}.fna > {output}"

rule gtdb_tree:
    input:
        diamond = "analysis/diamond_collect/gtdb.tsv",
        tree = "analysis/metadata/gtdb_clade.nwk"
    output:
        "output/gtdb.pdf"
    conda:
        "envs/r.yaml"
    script:
        "scripts/plot_gtdb.R"

rule phylophlan_input:
    input:
        chosen_faa_IIIa
    output:
        directory("analysis/IIIa")
    shell:
        "mkdir {output} && cp {input} {output}/"

# NB: usearch not under conda
rule phylophlan:
    input:
        work_dir = "analysis/IIIa",
        cfg = "metadata/phylophlan.cfg",
        maas = "metadata/phylophlan.tsv"
    output:
        treefile = "analysis/IIIa_phylophlan/IIIa.tre.treefile"
    conda:
        "envs/phylophlan.yaml"
    threads:
        workflow.cores
    shell:
        "phylophlan -i {input.work_dir} -t a -f {input.cfg} --diversity low --subsample full -d phylophlan --nproc {threads} --output_folder analysis --verbose --maas {input.maas}"
